"""
Simple name generator. Will create a random name with the following format:
{Adjectives}_{Bird Name}.
"""
import random

ADJECTIVES = [
	"abandoned", "able", "absolute", "adorable", "adventurous",
	"academic", "acceptable", "acclaimed", "accomplished", "accurate",
	"aching", "acidic", "acrobatic", "active", "actual", "adept",
	"admirable", "admired", "adolescent", "adorable", "adored", "advanced",
	"afraid", "affectionate", "aged", "aggravating", "aggressive", "agile",
	"agitated", "agonizing", "agreeable", "ajar", "alarmed", "alarming",
	"alert", "alienated", "alive", "all", "altruistic", "amazing",
	"ambitious", "ample", "amused", "amusing", "anchored", "ancient",
	"angelic", "angry", "anguished", "animated", "annual", "another",
	"antique", "anxious", "any", "apprehensive", "appropriate", "apt",
	"arctic", "arid", "aromatic", "artistic", "ashamed", "assured",
	"astonishing", "athletic", "attached", "attentive", "attractive",
	"austere", "authentic", "authorized", "automatic", "avaricious",
	"average", "aware", "awesome", "awful", "awkward", "babyish", "bad",
	"back", "baggy", "bare", "barren", "basic", "beautiful", "belated",
	"beloved", "beneficial", "better", "best", "bewitched", "big",
	"big-hearted", "biodegradable", "bite-sized", "bitter", "black",
	"black-and-white", "bland", "blank", "blaring", "bleak", "blind",
	"blissful", "blond", "blue", "blushing", "bogus", "boiling", "bold",
	"bony", "boring", "bossy", "both", "bouncy", "bountiful", "bowed",
	"brave", "breakable", "brief", "bright", "brilliant", "brisk", "broken",
	"bronze", "brown", "bruised", "bubbly", "bulky", "bumpy", "buoyant",
	"burdensome", "burly", "bustling", "busy", "buttery", "buzzing",
	"calculating", "calm", "candid", "canine", "capital", "carefree",
	"careful", "careless", "caring", "cautious", "cavernous", "celebrated",
	"charming", "cheap", "cheerful", "cheery", "chief", "chilly", "chubby",
	"circular", "classic", "clean", "clear", "clear-cut", "clever", "close",
	"closed", "cloudy", "clueless", "clumsy", "cluttered", "coarse", "cold",
	"colorful", "colorless", "colossal", "comfortable", "common",
	"compassionate", "competent", "complete", "complex", "complicated",
	"composed", "concerned", "concrete", "confused", "conscious",
	"considerate", "constant", "content", "conventional", "cooked", "cool",
	"cooperative", "coordinated", "corny", "corrupt", "costly",
	"courageous", "courteous", "crafty", "crazy", "creamy", "creative",
	"creepy", "criminal", "crisp", "critical", "crooked", "crowded",
	"cruel", "crushing", "cuddly", "cultivated", "cultured", "cumbersome",
	"curly", "curvy", "cute", "cylindrical", "damaged", "damp", "dangerous",
	"dapper", "daring", "darling", "dark", "dazzling", "dead", "deadly",
	"deafening", "dear", "dearest", "decent", "decimal", "decisive", "deep",
	"defenseless", "defensive", "defiant", "deficient", "definite",
	"definitive", "delayed", "delectable", "delicious", "delightful",
	"delirious", "demanding", "dense", "dental", "dependable", "dependent",
	"descriptive", "deserted", "detailed", "determined", "devoted",
	"different", "difficult", "digital", "diligent", "dim", "dimpled",
	"dimwitted", "direct", "disastrous", "discrete", "disfigured",
	"disgusting", "disloyal", "dismal", "distant", "downright", "dreary",
	"dirty", "disguised", "dishonest", "dismal", "distant", "distinct",
	"distorted", "dizzy", "dopey", "doting", "double", "downright", "drab",
	"drafty", "dramatic", "dreary", "droopy", "dry", "dual", "dull",
	"dutiful", "each", "eager", "earnest", "early", "easy", "easy-going",
	"ecstatic", "edible", "educated", "elaborate", "elastic", "elated",
	"elderly", "electric", "elegant", "elementary", "elliptical",
	"embarrassed", "embellished", "eminent", "emotional", "empty",
	"enchanted", "enchanting", "energetic", "enlightened", "enormous",
	"enraged", "entire", "envious", "equal", "equatorial", "essential",
	"esteemed", "ethical", "euphoric", "even", "evergreen", "everlasting",
	"every", "evil", "exalted", "excellent", "exemplary", "exhausted",
	"excitable", "excited", "exciting", "exotic", "expensive",
	"experienced", "expert", "extraneous", "extroverted", "extra-large",
	"extra-small", "fabulous", "failing", "faint", "fair", "faithful",
	"fake", "false", "familiar", "famous", "fancy", "fantastic", "far",
	"faraway", "far-flung", "far-off", "fast", "fat", "fatal", "fatherly",
	"favorable", "favorite", "fearful", "fearless", "feisty", "feline",
	"female", "feminine", "few", "fickle", "filthy", "fine", "finished",
	"firm", "first", "firsthand", "fitting", "fixed", "flaky", "flamboyant",
	"flashy", "flat", "flawed", "flawless", "flickering", "flimsy",
	"flippant", "flowery", "fluffy", "fluid", "flustered", "focused",
	"fond", "foolhardy", "foolish", "forceful", "forked", "formal",
	"forsaken", "forthright", "fortunate", "fragrant", "frail", "frank",
	"frayed", "free", "French", "fresh", "frequent", "friendly",
	"frightened", "frightening", "frigid", "frilly", "frizzy", "frivolous",
	"front", "frosty", "frozen", "frugal", "fruitful", "full", "fumbling",
	"functional", "funny", "fussy", "fuzzy", "gargantuan", "gaseous",
	"general", "generous", "gentle", "genuine", "giant", "giddy",
	"gigantic", "gifted", "giving", "glamorous", "glaring", "glass",
	"gleaming", "gleeful", "glistening", "glittering", "gloomy", "glorious",
	"glossy", "glum", "golden", "good", "good-natured", "gorgeous",
	"graceful", "gracious", "grand", "grandiose", "granular", "grateful",
	"grave", "gray", "great", "greedy", "green", "gregarious", "grim",
	"grimy", "gripping", "grizzled", "gross", "grotesque", "grouchy",
	"grounded", "growing", "growling", "grown", "grubby", "gruesome",
	"grumpy", "guilty", "gullible", "gummy", "hairy", "half", "handmade",
	"handsome", "handy", "happy", "happy-go-lucky", "hard", "hard-to-find",
	"harmful", "harmless", "harmonious", "harsh", "hasty", "hateful",
	"haunting", "healthy", "heartfelt", "hearty", "heavenly", "heavy",
	"hefty", "helpful", "helpless", "hidden", "hideous", "high",
	"high-level", "hilarious", "hoarse", "hollow", "homely", "honest",
	"honorable", "honored", "hopeful", "horrible", "hospitable", "hot",
	"huge", "humble", "humiliating", "humming", "humongous", "hungry",
	"hurtful", "husky", "icky", "icy", "ideal", "idealistic", "identical",
	"idle", "idiotic", "idolized", "ignorant", "ill", "illegal",
	"ill-fated", "ill-informed", "illiterate", "illustrious", "imaginary",
	"imaginative", "immaculate", "immaterial", "immediate", "immense",
	"impassioned", "impeccable", "impartial", "imperfect", "imperturbable",
	"impish", "impolite", "important", "impossible", "impractical",
	"impressionable", "impressive", "improbable", "impure", "inborn",
	"incomparable", "incompatible", "incomplete", "inconsequential",
	"incredible", "indelible", "inexperienced", "indolent", "infamous",
	"infantile", "infatuated", "inferior", "infinite", "informal",
	"innocent", "insecure", "insidious", "insignificant", "insistent",
	"instructive", "insubstantial", "intelligent", "intent", "intentional",
	"interesting", "internal", "international", "intrepid", "ironclad",
	"irresponsible", "irritating", "itchy", "jaded", "jagged", "jam-packed",
	"jaunty", "jealous", "jittery", "joint", "jolly", "jovial", "joyful",
	"joyous", "jubilant", "judicious", "juicy", "jumbo", "junior", "jumpy",
	"juvenile", "kaleidoscopic", "keen", "key", "kind", "kindhearted",
	"kindly", "klutzy", "knobby", "knotty", "knowledgeable", "knowing",
	"known", "kooky", "kosher", "lame", "lanky", "large", "last", "lasting",
	"late", "lavish", "lawful", "lazy", "leading", "lean", "leafy", "left",
	"legal", "legitimate", "light", "lighthearted", "likable", "likely",
	"limited", "limp", "limping", "linear", "lined", "liquid", "little",
	"live", "lively", "livid", "loathsome", "lone", "lonely", "long",
	"long-term", "loose", "lopsided", "lost", "loud", "lovable", "lovely",
	"loving", "low", "loyal", "lucky", "lumbering", "luminous", "lumpy",
	"lustrous", "luxurious", "mad", "made-up", "magnificent", "majestic",
	"major", "male", "mammoth", "married", "marvelous", "masculine",
	"massive", "mature", "meager", "mealy", "mean", "measly", "meaty",
	"medical", "mediocre", "medium", "meek", "mellow", "melodic",
	"memorable", "menacing", "merry", "messy", "metallic", "mild", "milky",
	"mindless", "miniature", "minor", "minty", "miserable", "miserly",
	"misguided", "misty", "mixed", "modern", "modest", "moist", "monstrous",
	"monthly", "monumental", "moral", "mortified", "motherly", "motionless",
	"mountainous", "muddy", "muffled", "multicolored", "mundane", "murky",
	"mushy", "musty", "muted", "mysterious", "naive", "narrow", "nasty",
	"natural", "naughty", "nautical", "near", "neat", "necessary", "needy",
	"negative", "neglected", "negligible", "neighboring", "nervous", "new",
	"next", "nice", "nifty", "nimble", "nippy", "nocturnal", "noisy",
	"nonstop", "normal", "notable", "noted", "noteworthy", "novel",
	"noxious", "numb", "nutritious", "nutty", "obedient", "obese", "oblong",
	"oily", "oblong", "obvious", "occasional", "odd", "oddball", "offbeat",
	"offensive", "official", "old", "old-fashioned", "only", "open",
	"optimal", "optimistic", "opulent", "orange", "orderly", "organic",
	"ornate", "ornery", "ordinary", "original", "other", "our", "outlying",
	"outgoing", "outlandish", "outrageous", "outstanding", "oval",
	"overcooked", "overdue", "overjoyed", "overlooked", "palatable", "pale",
	"paltry", "parallel", "parched", "partial", "passionate", "past",
	"pastel", "peaceful", "peppery", "perfect", "perfumed", "periodic",
	"perky", "personal", "pertinent", "pesky", "pessimistic", "petty",
	"phony", "physical", "piercing", "pink", "pitiful", "plain",
	"plaintive", "plastic", "playful", "pleasant", "pleased", "pleasing",
	"plump", "plush", "polished", "polite", "political", "pointed",
	"pointless", "poised", "poor", "popular", "portly", "posh", "positive",
	"possible", "potable", "powerful", "powerless", "practical", "precious",
	"present", "prestigious", "pretty", "precious", "previous", "pricey",
	"prickly", "primary", "prime", "pristine", "private", "prize",
	"probable", "productive", "profitable", "profuse", "proper", "proud",
	"prudent", "punctual", "pungent", "puny", "pure", "purple", "pushy",
	"putrid", "puzzled", "puzzling", "quaint", "qualified", "quarrelsome",
	"quarterly", "queasy", "querulous", "questionable", "quick",
	"quick-witted", "quiet", "quintessential", "quirky", "quixotic",
	"quizzical", "radiant", "ragged", "rapid", "rare", "rash", "raw",
	"recent", "reckless", "rectangular", "ready", "real", "realistic",
	"reasonable", "red", "reflecting", "regal", "regular", "reliable",
	"relieved", "remarkable", "remorseful", "remote", "repentant",
	"required", "respectful", "responsible", "repulsive", "revolving",
	"rewarding", "rich", "rigid", "right", "ringed", "ripe", "roasted",
	"robust", "rosy", "rotating", "rotten", "rough", "round", "rowdy",
	"royal", "rubbery", "rundown", "ruddy", "rude", "runny", "rural",
	"rusty", "sad", "safe", "salty", "same", "sandy", "sane", "sarcastic",
	"sardonic", "satisfied", "scaly", "scarce", "scared", "scary",
	"scented", "scholarly", "scientific", "scornful", "scratchy", "scrawny",
	"second", "secondary", "second-hand", "secret", "self-assured",
	"self-reliant", "selfish", "sentimental", "separate", "serene",
	"serious", "serpentine", "several", "severe", "shabby", "shadowy",
	"shady", "shallow", "shameful", "shameless", "sharp", "shimmering",
	"shiny", "shocked", "shocking", "shoddy", "short", "short-term",
	"showy", "shrill", "shy", "sick", "silent", "silky", "silly", "silver",
	"similar", "simple", "simplistic", "sinful", "single", "sizzling",
	"skeletal", "skinny", "sleepy", "slight", "slim", "slimy", "slippery",
	"slow", "slushy", "small", "smart", "smoggy", "smooth", "smug",
	"snappy", "snarling", "sneaky", "sniveling", "snoopy", "sociable",
	"soft", "soggy", "solid", "somber", "some", "spherical",
	"sophisticated", "sore", "sorrowful", "soulful", "soupy", "sour",
	"Spanish", "sparkling", "sparse", "specific", "spectacular", "speedy",
	"spicy", "spiffy", "spirited", "spiteful", "splendid", "spotless",
	"spotted", "spry", "square", "squeaky", "squiggly", "stable", "staid",
	"stained", "stale", "standard", "starchy", "stark", "starry", "steep",
	"sticky", "stiff", "stimulating", "stingy", "stormy", "straight",
	"strange", "steel", "strict", "strident", "striking", "striped",
	"strong", "studious", "stunning", "stupendous", "stupid", "sturdy",
	"stylish", "subdued", "submissive", "substantial", "subtle", "suburban",
	"sudden", "sugary", "sunny", "super", "superb", "superficial",
	"superior", "supportive", "sure-footed", "surprised", "suspicious",
	"svelte", "sweaty", "sweet", "sweltering", "swift", "sympathetic",
	"tall", "talkative", "tame", "tan", "tangible", "tart", "tasty",
	"tattered", "taut", "tedious", "teeming", "tempting", "tender", "tense",
	"tepid", "terrible", "terrific", "testy", "thankful", "that", "these",
	"thick", "thin", "third", "thirsty", "this", "thorough", "thorny",
	"those", "thoughtful", "threadbare", "thrifty", "thunderous", "tidy",
	"tight", "timely", "tinted", "tiny", "tired", "torn", "total", "tough",
	"traumatic", "treasured", "tremendous", "tragic", "trained",
	"tremendous", "triangular", "tricky", "trifling", "trim", "trivial",
	"troubled", "true", "trusting", "trustworthy", "trusty", "truthful",
	"tubby", "turbulent", "twin", "ugly", "ultimate", "unacceptable",
	"unaware", "uncomfortable", "uncommon", "unconscious", "understated",
	"unequaled", "uneven", "unfinished", "unfit", "unfolded", "unfortunate",
	"unhappy", "unhealthy", "uniform", "unimportant", "unique", "united",
	"unkempt", "unknown", "unlawful", "unlined", "unlucky", "unnatural",
	"unpleasant", "unrealistic", "unripe", "unruly", "unselfish",
	"unsightly", "unsteady", "unsung", "untidy", "untimely", "untried",
	"untrue", "unused", "unusual", "unwelcome", "unwieldy", "unwilling",
	"unwitting", "unwritten", "upbeat", "upright", "upset", "urban",
	"usable", "used", "useful", "useless", "utilized", "utter", "vacant",
	"vague", "vain", "valid", "valuable", "vapid", "variable", "vast",
	"velvety", "venerated", "vengeful", "verifiable", "vibrant", "vicious",
	"victorious", "vigilant", "vigorous", "villainous", "violet", "violent",
	"virtual", "virtuous", "visible", "vital", "vivacious", "vivid",
	"voluminous", "wan", "warlike", "warm", "warmhearted", "warped", "wary",
	"wasteful", "watchful", "waterlogged", "watery", "wavy", "wealthy",
	"weak", "weary", "webbed", "wee", "weekly", "weepy", "weighty", "weird",
	"welcome", "well-documented", "well-groomed", "well-informed",
	"well-lit", "well-made", "well-off", "well-to-do", "well-worn", "wet",
	"which", "whimsical", "whirlwind", "whispered", "white", "whole",
	"whopping", "wicked", "wide", "wide-eyed", "wiggly", "wild", "willing",
	"wilted", "winding", "windy", "winged", "wiry", "wise", "witty",
	"wobbly", "woeful", "wonderful", "wooden", "woozy", "wordy", "worldly",
	"worn", "worried", "worrisome", "worse", "worst", "worthless",
	"worthwhile", "worthy", "wrathful", "wretched", "writhing", "wrong",
	"wry", "yawning", "yearly", "yellow", "yellowish", "young", "youthful",
	"yummy", "zany", "zealous", "zesty", "zigzag"
]


BIRDS = [
	"accentor", "adjutant", "albatross", "alethe", "anhinga", "ani",
	"antbird", "antpitta", "antshrike", "antthrush", "antwren", "apalis",
	"apostlebird", "aracari", "argus", "asity", "astrapia", "auk", "auklet",
	"avocet", "avocetbill", "awlbill", "babbler", "bananaquit", "barbet",
	"barbthroat", "bare-eye", "bateleur", "batis", "baza", "bee-eater",
	"bellbird", "bernieria", "berrypecker", "besra", "bird-of-paradise",
	"bittern", "blackbird", "blackcap", "blackeye", "bleeding-heart",
	"blossomcrown", "bluebill", "bluebird", "bluethroat", "boatbill",
	"bobolink", "bobwhite", "bokmakierie", "boobook", "booby", "bowerbird",
	"brambling", "brilliant", "bristlebill", "bristlebird", "bristlefront",
	"bristlehead", "broadbill", "bronzewing", "brushturkey", "bufflehead",
	"bulbul", "bullfinch", "bunting", "bushchat", "bush-hen", "bushshrike",
	"bushtit", "bustard", "butcherbird", "buttonquail", "buzzard",
	"cachalote", "cacique", "camaroptera", "canastero", "canvasback",
	"capercaillie", "caracara", "cardinal", "carib", "cassowary", "catbird",
	"chachalaca", "chaffinch", "chat", "chickadee", "chicken", "chiffchaff",
	"chlorophonia", "chough", "chuck-will's-widow", "cicadabird",
	"cinclodes", "cisticola", "cochoa", "cock-of-the-rock", "comet",
	"condor", "conebill", "coot", "coquette", "cormorant", "coronet",
	"cotinga", "coua", "coucal", "courser", "cowbird", "crab-plover",
	"crake", "crane", "creeper", "crombec", "crossbill", "crow", "cuckoo",
	"cuckoo-dove", "cuckoo-hawk", "cuckooshrike", "curassow", "curlew",
	"currawong", "darter", "dickcissel", "dipper", "dodo", "dollarbird",
	"donacobius", "dotterel", "dove", "dowitcher", "drongo", "duck",
	"dunlin", "dunnock", "eagle", "eagle-owl", "egret", "eider", "elaenia",
	"‘elepaio", "emerald", "emu", "eremomela", "euphonia", "fairy",
	"fairy-bluebird", "fairywren", "falcon", "falconet", "fantail",
	"fernwren", "fieldfare", "figbird", "finch", "finfoot", "fireback",
	"firecrown", "firefinch", "firewood-gatherer", "fiscal", "flameback",
	"flamingo", "flicker", "florican", "flowerpecker", "flufftail",
	"flycatcher", "foliage-gleaner", "forktail", "francolin", "friarbird",
	"frigatebird", "frogmouth", "fruiteater", "fulmar", "fulvetta",
	"gadwall", "gallinule", "gallito", "gannet", "garganey", "gerygone",
	"gnatcatcher", "gnateater", "gnatwren", "go-away-bird", "godwit",
	"goldcrest", "goldeneye", "goldenthroat", "goldfinch", "goose",
	"goshawk", "grackle", "grassbird", "grassquit", "grasswren", "grebe",
	"greenbul", "greenfinch", "greenshank", "grenadier", "grosbeak",
	"grouse", "guan", "guillemot", "guineafowl", "gull", "hamerkop",
	"hardhead", "harrier", "harrier-hawk", "hawfinch", "hawk", "hawk-eagle",
	"hawk-owl", "helmetcrest", "helmetshrike", "hermit", "heron",
	"hillstar", "hoatzin", "hobby", "honeybird", "honeycreeper",
	"honeyeater", "honeyguide", "hoopoe", "hoopoe-lark", "hornbill",
	"hornero", "hummingbird", "hypocolius", "ibis", "ibisbill", "iiwi",
	"illadopsis", "inca", "iora", "jabiru", "jacamar", "jacana", "jackdaw",
	"jacobin", "jaeger", "jay", "jewelfront", "junco", "junglefowl", "kagu",
	"kestrel", "killdeer", "kingbird", "kingfisher", "kinglet", "kiskadee",
	"kite", "kittiwake", "kiwi", "knot", "koel", "kōkako", "kookaburra",
	"korhaan", "lancebill", "lapwing", "lark", "laughingthrush", "leafbird",
	"limpkin", "linnet", "logrunner", "longbill", "longclaw", "longspur",
	"loon", "lyrebird", "magpie", "magpie-lark", "magpie-robin", "maleo",
	"malkoha", "mallard", "malleefowl", "manakin", "mango", "martin",
	"meadowlark", "megapode", "merganser", "merlin", "mesia", "mesite",
	"metaltail", "miner", "minivet", "minla", "mistletoebird",
	"mockingbird", "monal", "monal-partridge", "monarch", "monjita",
	"monklet", "moorhen", "motmot", "mountaineer", "mountaingem",
	"mousebird", "munia", "murre", "murrelet", "myna", "nativehen",
	"needletail", "nene", "nighthawk", "nightingale", "nightjar", "niltava",
	"noddy", "nothura", "nunbird", "nunlet", "nutcracker", "nuthatch",
	"oilbird", "openbill", "oriole", "oropendola", "osprey", "ostrich",
	"ouzel", "ovenbird", "owl", "oxpecker", "oystercatcher",
	"painted-snipe", "palmchat", "pardalote", "parrotbill", "parrotfinch",
	"partridge", "parula", "pauraque", "peacock-pheasant", "peafowl",
	"pelican", "penguin", "peppershrike", "petrel", "petronia", "pewee",
	"phalarope", "pheasant", "phoebe", "piapiac", "picathartes", "piclet",
	"piculet", "piedtail", "pigeon", "pilotbird", "pintail", "pipit",
	"pitta", "plains-wanderer", "plantain-eater", "plantcutter", "plover",
	"plovercrest", "plumeleteer", "pochard", "poorwill", "potoo",
	"pratincole", "prinia", "prion", "ptarmigan", "puffbird", "puffin",
	"puffleg", "pytilia", "quail", "quail-dove", "quail-plover",
	"quail-thrush", "quelea", "quetzal", "rail", "raven", "rayadito",
	"razorbill", "redhead", "redpoll", "redshank", "redstart", "reedling",
	"rhea", "riflebird", "rifleman", "robin", "rockjumper", "roller",
	"rook", "rosefinch", "ruby", "ruff", "sabrewing", "saddleback",
	"saltator", "sanderling", "sandgrouse", "sandpiper", "sapphire",
	"sapsucker", "satinbird", "scaup", "schiffornis", "scimitarbill",
	"scoter", "screamer", "scrubbird", "scrubfowl", "scrubwren",
	"scythebill", "secretarybird", "seedeater", "seedsnipe", "seriema",
	"shag", "sharpbill", "sheartail", "shearwater", "sheathbill",
	"sheldgoose", "shelduck", "shikra", "shoebill", "shortwing", "shoveler",
	"shrike", "shrike-thrush", "shrike-tit", "sibia", "sicklebill",
	"silktail", "silvereye", "siskin", "sittella", "skimmer", "skua",
	"skylark", "smew", "snipe", "snowcap", "snowcock", "snowfinch",
	"solitaire", "songlark", "sora", "spadebill", "sparrow", "sparrowhawk",
	"spatuletail", "spinebill", "spinetail", "spinifexbird", "spoonbill",
	"spurfowl", "starfrontlet", "starling", "starthroat", "stilt", "stint",
	"stitchbird", "stonechat", "stone-curlew", "stork", "streamertail",
	"sugarbird", "sunangel", "sunbeam", "sunbird", "sunbird-asity",
	"sunbittern", "sungem", "sungrebe", "surfbird", "swallow", "swamphen",
	"swan", "swift", "swiftlet", "sylph", "tailorbird", "takahē", "tanager",
	"tapaculo", "tattler", "tchagra", "teal", "tern", "thick-knee",
	"thornbill", "thorntail", "thrasher", "thrush", "tinamou", "tinkerbird",
	"tit", "titmouse", "tody", "tody-flycatcher", "topaz", "toucan",
	"toucanet", "towhee", "tragopan", "trainbearer", "treecreeper",
	"treeswift", "trembler", "triller", "trogon", "tropicbird", "trumpeter",
	"tui", "turaco", "turkey", "turnstone", "twinspot", "tyrannulet",
	"tyrant", "umbrellabird", "vanga", "veery", "velvetbreast", "verdin",
	"violetear", "vireo", "visorbearer", "vulture", "wagtail",
	"wallcreeper", "warbler", "watercock", "waterhen", "waterthrush",
	"wattlebird", "wattle-eye", "waxbill", "waxwing", "weaver", "weebill",
	"weka", "wheatear", "whimbrel", "whipbird", "whip-poor-will",
	"whistler", "white-eye", "whiteface", "whitethroat", "whitetip",
	"whydah", "widowbird", "wigeon", "willet", "winter", "woodcock",
	"woodcreeper", "woodhen", "woodlark", "woodnymph", "woodpecker",
	"woodstar", "woodswallow", "wren", "wrenthrush", "wrentit", "wrybill",
	"wryneck", "xenops", "yellowhammer", "yellowlegs", "yellownape",
	"yellowthroat", "yuhina"
]


def generate_name():
    """
    Generate a random name with the following format: {Adjectives}_{Bird Name}.

    :return: the random name.
    :rtype: str
    """
    return "_".join([random.choice(ADJECTIVES), random.choice(BIRDS)])
